let phones = [
  { id: 1, brand: "Apple", title: "Apple iPhone 16 Pro Max – Stunning 6.9-inch display, Titanium design, advanced triple camera system.", image: ["/image_apple/iPhone16ProMax-artguru.png","/image_apple/iphone16pro.png"], price: 1399, discounted: true, discount_percent: 10, condition: "A" },
  { id: 2, brand: "Apple", title: "Apple iPhone 16 Pro – Powerful A18 chip, sleek titanium build, and ProMotion display.", image: ["/image_apple/iphone16pro.png"], price: 1199, discounted: true, discount_percent: 8, condition: "B" },
  { id: 3, brand: "Apple", title: "Apple iPhone 16 – Brilliant performance, vibrant OLED display, and elegant design.", image: ["/image_apple/iphone16.png"], price: 999, discounted: false, discount_percent: 0, condition: "C" },
  { id: 4, brand: "Apple", title: "Apple iPhone 16 Plus – Large 6.7-inch display, long battery life, and smooth performance.", image: ["/image_apple/iphone16.png"], price: 1099, discounted: false, discount_percent: 0, condition: "A" },
  { id: 5, brand: "Apple", title: "Apple iPhone 15 Pro Max – Premium design, 6.7-inch screen, and powerful A17 Pro chip.", image: ["/image_apple/iphone16.png"], price: 1199, discounted: true, discount_percent: 12, condition: "B" },
  { id: 6, brand: "Apple", title: "Apple iPhone 15 Pro – Compact power with advanced camera and titanium frame.", image: ["/image_apple/iphone16.png"], price: 999, discounted: false, discount_percent: 0, condition: "C" },
  { id: 7, brand: "Apple", title: "Apple iPhone 15 – Smooth performance, bright OLED display, and elegant finish.", image: ["/image_apple/iphone16.png"], price: 799, discounted: true, discount_percent: 5, condition: "A" },
  { id: 8, brand: "Apple", title: "Apple iPhone 15 Plus – Big screen experience with long battery life and A16 chip.", image: ["/image_apple/iphone16.png"], price: 899, discounted: false, discount_percent: 0, condition: "B" },
  { id: 9, brand: "Apple", title: "Apple iPhone SE (2024) – Compact design, powerful A16 chip, and excellent value.", image: ["/image_apple/iphone16.png"], price: 429, discounted: true, discount_percent: 15, condition: "C" },
  { id: 10, brand: "Apple", title: "Apple iPhone 14 – Classic design, dependable performance, and great camera quality.", image: ["/image_apple/iphone16.png"], price: 599, discounted: false, discount_percent: 0, condition: "A" },
  { id: 11, brand: "Android", title: "Honor X7d smartphone 8GB RAM, 256GB Storage, 6500mAh battery, Snapdragon 685, 108MP Main Camera, 8MP Selfie Camera, 6.77 Inch dispaly, 4G, Velvet Black", image: ["/image_android/Honor_X7d.png","/image_android/Honor_X7d_2.png","/image_android/Honor_X7d_3.png"], price: 100, discounted: true, discount_percent: 10, condition: "A" },
  { id: 12, brand: "Android", title: "Oppo Reno 14F 5G 12Gb 256GB Luminous Green.", image: ["/image_android/Oppo Reno12 Pro 5G.png"], price: 599, discounted: true, discount_percent: 15, condition: "B" },
  { id: 13, brand: "Android", title: "Xiaomi Redmi A5 Smartphone 4GB + 64GB, Battery 5200mAh Octa-Core Processor, 32MP Al Dual Camera, 6.88 Inch Display, Fingerprint and Face Unlock, Lake Green", image: ["/image_android/Redmi_A5.png","/image_android/Redmi_A5_2.png","/image_android/Redmi_A5_3.png","/image_android/Redmi_A5_4.png"], price: 60, discounted: true, discount_percent: 8, condition: "C" },
  { id: 14, brand: "Android", title: "Xiaomi Redmi Note 14 Pro Smartphone, 8 + 256GB, Black, 200MP Professional AI Camera, 5500mAh Battery, 32MP Selfie Camera, AI Functions | 1 year manufacturer warranty", image: ["/image_android/redmi_note_14.png","/image_android/redmi_note_142.png","/image_android/redmi_note_14_3.png"], price: 200, discounted: true, discount_percent: 20, condition: "B" },
  { id: 15, brand: "Android", title: "SAMSUNG Galaxy A07 A075F 64GB 4GB RAM GSM Unlocked International", image: ["/image_android/Samsung_Galaxy_A07_Dual.png","/image_android/Samsung_Galaxy_A07_Dual_2.png","/image_android/Samsung_Galaxy_A07_Dual_3.png","/image_android/Samsung_Galaxy_A07_Dual_4.png","/image_android/Samsung_Galaxy_A07_Dual_5.png","/image_android/Samsung_Galaxy_A07_Dual_6.png"], price: 80, discounted: true, discount_percent: 18, condition: "A" },
  { id: 16, brand: "Android", title: "Samsung Galaxy A17 LTE, Android Smartphone, 128GB Storage, 4GB RAM, Gray, 6x OS Upgrades, Large Display, 50MP OIS Camera", image: ["/image_android/Samsung_Galaxy_A17.png","/image_android/Samsung_Galaxy_A17_2.png"], price: 100, discounted: true, discount_percent: 15, condition: "C" },
  { id: 17, brand: "Android", title: "Samsung Galaxy S25 Ultra AI Phone, 512GB Storage, 12GB RAM, Titanium Black, Android Smartphone, 200MP Camera, S Pen, Long Battery", image: ["/image_android/samsung_s25_ultra.png","/image_android/samsung_s25_ultra_white.png","/image_android/samsung_s25_ultra_blue.png"], price: 1150, discounted: false, discount_percent: 0, condition: "A" },
  { id: 18, brand: "Android", title: "SAMSUNG Galaxy M55 5G+ 4G LTE Factory Unlocked 256GB/8GB Cell Phone INT.V GRN", image: ["/image_android/Samsung_Galaxy_M55_5G.png","/image_android/Samsung_Galaxy_M55_5G_3.png"], price: 180, discounted: false, discount_percent: 0, condition: "B" },
  { id: 19, brand: "Android", title: "Xiaomi Redmi Note 14 Global 8GB RAM 256GB ROM 4G Unlocked AMOLED 120Hz", image: ["/image_android/redmi_note_14.png","/image_android/redmi_note_142.png","/image_android/redmi_note_14_3.png"], price: 200, discounted: false, discount_percent: 0, condition: "A" },
  { id: 20, brand: "Android", title: "Samsung Galaxy Z Fold 6 5G - Snapdragon 8 Gen 3, 7.6 OLED, 50MP Camera", image: ["/image_android/SAMSUNG Galaxy Z Fold6.jpg",], price: 950, discounted: false, discount_percent: 0, condition: "B" },
  { id: 21, brand: "Android", title: "Samsung Galaxy A56 5G, Android Smartphone, 256GB Storage, 8GB RAM, Awesome Olive, 6x OS Upgrades, Large Display, Long Battery", image: ["/image_android/Samsung_Galaxy_A56 5G_Android_Smartphone.png","/image_android/Samsung_Galaxy_A56 5G_Android_Smartphone_2.png"], price: 300, discounted: false, discount_percent: 0, condition: "B" },
  { id: 22, brand: "Android", title: "Samsung Galaxy S25 FE, 5G, Smartphone, Android, 256GB Storage, 8GB RAM, Navy, Octa Core, 1.3GHz, 6.7-inch, Full HD, 120Hz-1", image: ["/image_android/Samsung_Galaxy_S25_FE_5G_Smartphone_Android_256GB_Storage.png","/image_android/Samsung_Galaxy_S25_FE_5G_Smartphone_Android_256GB_Storage_2.jpg"], price: 350, discounted: false, discount_percent: 0, condition: "C" },
  
];

if (localStorage.getItem('phonesUser')) {
  const phonesUser = JSON.parse(localStorage.getItem('phonesUser'));
  phones = phones.concat(phonesUser);
}
console.log(phones)